const layoutData = [
  { value: "mudroom", label: "Mudroom" },
  { value: "diningRoom", label: "Dining Room" },
  { value: "livingRoom", label: "Living Room" },
  { value: "office", label: "Office" },
  { value: "playroom", label: "Playroom" },
  { value: "kitchen", label: "Kitchen" },
  { value: "driveway", label: "Driveway" },
  { value: "basement", label: "Basement" },
  { value: "attic", label: "Attic" },
  { value: "garage", label: "Garage" },
  { value: "frontYard", label: "Front Yard" },
  { value: "frontPorch", label: "Front Porch" },
  { value: "sideWalk", label: "Side Walk" },
  { value: "backYard", label: "Back Yard" },
  { value: "deck", label: "Deck" },
  { value: "pool", label: "Pool" },
  { value: "spa", label: "Spa" },
  { value: "halfBath", label: "Half Bath" },
  { value: "threeQuarterBath", label: "3/4 Bath" },
  { value: "fullBath", label: "Full Bath" },
  { value: "masterBedroom", label: "Master Bedroom" },
  { value: "guestBedroom", label: "Guest Bedroom" },
  { value: "kidsBedroom", label: "Kids Bedroom" },
  { value: "roommateBedroom", label: "Roommate Bedroom" },
  { value: "playSet", label: "Play Set" },
  { value: "kidsBedroom", label: "Kids Bedroom" },
  { value: "kidsBedroom", label: "Kids Bedroom" },
  { value: "kidsBedroom", label: "Kids Bedroom" },
  { value: "roommateBedroom", label: "Roommate Bedroom" },
  { value: "roommateBedroom", label: "Roommate Bedroom" },
  { value: "roommateBedroom", label: "Roommate Bedroom" },
  { value: "guestBedroom", label: "Guest Bedroom" },
  { value: "guestBedroom", label: "Guest Bedroom" },
  { value: "halfBath", label: "Half Bath" },
  { value: "threeQuarterBath", label: "3/4 Bath" },
  { value: "fullBath", label: "Full Bath" },
  { value: "halfBath", label: "Half Bath" },
  { value: "threeQuarterBath", label: "3/4 Bath" },
  { value: "fullBath", label: "Full Bath" },
 
];

export default layoutData;
